[project @ 2000-12-05 05:56:02 by mdz] Simplify all question names, add confirm option

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -2,45 +2,62 @@
 
 set -e
 
+PREFERENCES=/etc/apt/listchanges.conf
+APT_CONFIG=/etc/apt/apt.conf.d/20-apt-listchanges.conf
+
+mkdir -p /etc/apt/apt.conf.d
+
 # Source debconf library.
 . /usr/share/debconf/confmodule
 
+# Wipe out any old configuration (preserve permissions, though)
+[ -f "$APT_CONFIG" ] && : > $APT_CONFIG
+[ -f "$PREFERENCES" ] && : > $PREFERENCES
+
+# Should we hook into apt?
 db_get apt-listchanges/apt-hook-p
 
-# This was mostly snarfed from debconf
 if [ "$RET" = "true" ]; then
-
-	# Add ourselves to apt.conf
-
-	# Create /etc/apt/apt.conf if it doesn't already exist
-	if [ ! -e /etc/apt/apt.conf ]; then
-		mkdir -p /etc/apt/ 2>/dev/null || true
-		touch /etc/apt/apt.conf
-	fi
-
-	if ! grep -q apt-listchanges /etc/apt/apt.conf; then
-	  cat <<EOF >> /etc/apt/apt.conf
-// apt-listchanges: Display changelogs for packages before they are installed.
-Dpkg::Pre-Install-Pkgs { "/usr/bin/apt-listchanges --apt"; }; // apt-listchanges
+  cat <<EOF >> $APT_CONFIG
+DPkg::Pre-Install-Pkgs { "/usr/bin/apt-listchanges --apt"; };
 EOF
-	fi
-elif [ "$RET" = "false" ]; then
-	# Remove ourselves from apt.conf
-	cp /etc/apt/apt.conf /etc/apt/apt.conf.apt-listchanges-old
-	grep -v apt-listchanges /etc/apt/apt.conf.apt-listchanges-old > /etc/apt/apt.conf
-	rm -f /etc/apt/apt.conf.apt-listchanges-old
+else
+  rm -f $APT_CONFIG
 fi
 
-[ -f /etc/apt-listchanges.conf ] && \
-    cp /etc/apt-listchanges.conf /etc/apt-listchanges.conf.old
+echo "# Changes made here will be lost.  Please use dpkg-reconfigure apt-listchanges" >> $PREFERENCES
 
-db_get apt-listchanges/apt-mode-frontend
+db_get apt-listchanges/frontend
 
-echo "apt-mode-frontend=$RET" > /etc/apt-listchanges.conf
+echo "frontend=$RET" >> $PREFERENCES
 
-db_get apt-listchanges/apt-mode-email-address
+db_get apt-listchanges/email-address
 
-echo "apt-mode-email-address=$RET" >> /etc/apt-listchanges.conf
+echo "email-address=$RET" >> $PREFERENCES
+
+db_get apt-listchanges/confirm
+if [ "$RET" = "true" ]; then
+  echo "confirm=yes" >> $PREFERENCES
+else
+  echo "confirm=no" >> $PREFERENCES
+fi
+
+## Cleanup from older versions (1.13 and earlier)
+
+# Remove config files from older versions
+rm -f /etc/apt-listchanges.conf /etc/apt-listchanges.conf.old
+
+# We used to add ourselves to apt.conf; remove ourselves
+if [ -e /etc/apt/apt.conf ]; then
+        cp /etc/apt/apt.conf /etc/apt/apt.conf.old
+        (grep -v apt-listchanges /etc/apt/apt.conf.old > /etc/apt/apt.conf) || true
+        rm -f /etc/apt/apt.conf.old
+        if [ ! -s /etc/apt/apt.conf ]; then
+                rm -f /etc/apt/apt.conf
+                rmdir --ignore-fail-on-non-empty -p /etc/apt/
+        fi
+fi
+
 
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
