[project @ 2000-12-11 18:57:57 by mdz] Go back to pre-0.4 apt code

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -11,18 +11,43 @@ mkdir -p /etc/apt/apt.conf.d
 . /usr/share/debconf/confmodule
 
 # Wipe out any old configuration (preserve permissions, though)
-[ -f "$APT_CONFIG" ] && : > $APT_CONFIG
+##waiting for apt 0.4## [ -f "$APT_CONFIG" ] && : > $APT_CONFIG 
 [ -f "$PREFERENCES" ] && : > $PREFERENCES
 
 # Should we hook into apt?
 db_get apt-listchanges/apt-hook-p
 
+##waiting for apt 0.4##  if [ "$RET" = "true" ]; then
+##waiting for apt 0.4##    cat <<EOF >> $APT_CONFIG
+##waiting for apt 0.4##  DPkg::Pre-Install-Pkgs { "/usr/bin/apt-listchanges --apt"; };
+##waiting for apt 0.4##  EOF
+##waiting for apt 0.4##  else
+##waiting for apt 0.4##    rm -f $APT_CONFIG
+##waiting for apt 0.4##  fi
+
+# This was mostly snarfed from debconf
 if [ "$RET" = "true" ]; then
-  cat <<EOF >> $APT_CONFIG
-DPkg::Pre-Install-Pkgs { "/usr/bin/apt-listchanges --apt"; };
+
+    # Add ourselves to apt.conf
+
+    # Create /etc/apt/apt.conf if it doesn't already exist
+    if [ ! -e /etc/apt/apt.conf ]; then
+	mkdir -p /etc/apt/ 2>/dev/null || true
+	touch /etc/apt/apt.conf
+    fi
+
+    if ! grep -q apt-listchanges /etc/apt/apt.conf; then
+	cat <<EOF >> /etc/apt/apt.conf
+// apt-listchanges: Display changelogs for packages before they are installed.
+Dpkg::Pre-Install-Pkgs { "/usr/bin/apt-listchanges --apt"; }; // apt-listchanges
 EOF
-else
-  rm -f $APT_CONFIG
+    fi
+
+elif [ "$RET" = "false" ]; then
+    # Remove ourselves from apt.conf
+    cp /etc/apt/apt.conf /etc/apt/apt.conf.apt-listchanges-old
+    grep -v apt-listchanges /etc/apt/apt.conf.apt-listchanges-old > /etc/apt/apt.conf
+    rm -f /etc/apt/apt.conf.apt-listchanges-old
 fi
 
 echo "# Changes made here will be lost.  Please use dpkg-reconfigure apt-listchanges" >> $PREFERENCES
@@ -47,16 +72,16 @@ fi
 # Remove config files from older versions
 rm -f /etc/apt-listchanges.conf /etc/apt-listchanges.conf.old
 
-# We used to add ourselves to apt.conf; remove ourselves
-if [ -e /etc/apt/apt.conf ]; then
-        cp /etc/apt/apt.conf /etc/apt/apt.conf.old
-        (grep -v apt-listchanges /etc/apt/apt.conf.old > /etc/apt/apt.conf) || true
-        rm -f /etc/apt/apt.conf.old
-        if [ ! -s /etc/apt/apt.conf ]; then
-                rm -f /etc/apt/apt.conf
-                rmdir --ignore-fail-on-non-empty -p /etc/apt/
-        fi
-fi
+##waiting for apt 0.4## # We used to add ourselves to apt.conf; remove ourselves
+##waiting for apt 0.4## if [ -e /etc/apt/apt.conf ]; then
+##waiting for apt 0.4##         cp /etc/apt/apt.conf /etc/apt/apt.conf.old
+##waiting for apt 0.4##         (grep -v apt-listchanges /etc/apt/apt.conf.old > /etc/apt/apt.conf) || true
+##waiting for apt 0.4##         rm -f /etc/apt/apt.conf.old
+##waiting for apt 0.4##         if [ ! -s /etc/apt/apt.conf ]; then
+##waiting for apt 0.4##                 rm -f /etc/apt/apt.conf
+##waiting for apt 0.4##                 rmdir --ignore-fail-on-non-empty -p /etc/apt/
+##waiting for apt 0.4##         fi
+##waiting for apt 0.4## fi
 
 
 # dh_installdeb will replace this with shell code automatically
