[project @ 2001-03-05 03:01:33 by mdz] apt 0.5.1 is now required, roll out the /etc/apt/apt.conf.d stuff

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -2,84 +2,64 @@
 
 set -e
 
+action=$1
+
 PREFERENCES=/etc/apt/listchanges.conf
-APT_CONFIG=/etc/apt/apt.conf.d/20-apt-listchanges.conf
 
-mkdir -p /etc/apt/apt.conf.d
+if [ "$action" = "configure" ]; then
+    version=$2
+    # Source debconf library.
+    . /usr/share/debconf/confmodule
 
-# Source debconf library.
-. /usr/share/debconf/confmodule
+    db_get apt-listchanges/overwrite_etc_apt_listchanges_conf
+    if [ "$RET" = "true" -o ! -e "$PREFERENCES" ]; then
+	[ -f "$PREFERENCES" ] && cp $PREFERENCES $PREFERENCES.old
+	: > $PREFERENCES
 
-# Should we hook into apt?
-db_get apt-listchanges/apt-hook-p
+	db_get apt-listchanges/frontend
+	echo "frontend=$RET" >> $PREFERENCES
 
-##waiting for apt 0.4##  if [ "$RET" = "true" ]; then
-##waiting for apt 0.4##    cat <<EOF > $APT_CONFIG
-##waiting for apt 0.4##  DPkg::Pre-Install-Pkgs { "/usr/bin/apt-listchanges --apt"; };
-##waiting for apt 0.4##  EOF
-##waiting for apt 0.4##  else
-##waiting for apt 0.4##    rm -f $APT_CONFIG
-##waiting for apt 0.4##  fi
+	db_get apt-listchanges/email-address
+	echo "email-address=$RET" >> $PREFERENCES
 
-# This was mostly snarfed from debconf
-if [ "$RET" = "true" ]; then
+	db_get apt-listchanges/confirm
+	if [ "$RET" = "true" ]; then
+	  echo "apt-mode-confirm=yes" >> $PREFERENCES
+	else
+	  echo "apt-mode-confirm=no" >> $PREFERENCES
+	fi
 
-    # Add ourselves to apt.conf
+	db_get apt-listchanges/apt-hook-p
+	if [ "$RET" = "true" ]; then
+	  echo "apt-mode-run=yes" >> $PREFERENCES
+	else
+          echo "apt-mode-run=no" >> $PREFERENCES
+	fi
 
-    # Create /etc/apt/apt.conf if it doesn't already exist
-    if [ ! -e /etc/apt/apt.conf ]; then
-	mkdir -p /etc/apt/ 2>/dev/null || true
-	touch /etc/apt/apt.conf
+	rm -f $PREFERENCES.old
     fi
 
-    if ! grep -q apt-listchanges /etc/apt/apt.conf; then
-	cat <<EOF >> /etc/apt/apt.conf
-// apt-listchanges: Display changelogs for packages before they are installed.
-Dpkg::Pre-Install-Pkgs { "/usr/bin/apt-listchanges --apt"; };
-EOF
-    fi
+    ## Cleanup from older versions
 
-elif [ "$RET" = "false" ]; then
-    # Remove ourselves from apt.conf
-    cp /etc/apt/apt.conf /etc/apt/apt.conf.apt-listchanges-old
-    grep -v apt-listchanges /etc/apt/apt.conf.apt-listchanges-old > /etc/apt/apt.conf
-    rm -f /etc/apt/apt.conf.apt-listchanges-old
-fi
+    # Remove config files from older versions (pre-1.14)
+    rm -f /etc/apt-listchanges.conf /etc/apt-listchanges.conf.old
 
-db_get apt-listchanges/overwrite_etc_apt_listchanges_conf
-if [ "$RET" = "true" -o ! -e "$PREFERENCES" ]; then
-    [ -f "$PREFERENCES" ] && : > $PREFERENCES
+    # We used to add ourselves to apt.conf (pre-1.34); remove ourselves
+    if dpkg --compare-versions "$version" lt 1.34 \
+	&& test -e /etc/apt/apt.conf; then
+	cp /etc/apt/apt.conf /etc/apt/apt.conf.old
 
-    db_get apt-listchanges/frontend
-    echo "frontend=$RET" >> $PREFERENCES
+	(grep -v apt-listchanges /etc/apt/apt.conf.old \
+	    > /etc/apt/apt.conf) || true
 
-    db_get apt-listchanges/email-address
-    echo "email-address=$RET" >> $PREFERENCES
+	rm -f /etc/apt/apt.conf.old
 
-    db_get apt-listchanges/confirm
-    if [ "$RET" = "true" ]; then
-      echo "apt-mode-confirm=yes" >> $PREFERENCES
-    else
-      echo "apt-mode-confirm=no" >> $PREFERENCES
+	if [ ! -s /etc/apt/apt.conf ]; then
+	    rm -f /etc/apt/apt.conf
+	    rmdir --ignore-fail-on-non-empty -p /etc/apt/
+	fi
     fi
 fi
-
-## Cleanup from older versions (pre-1.14 and earlier)
-
-# Remove config files from older versions
-rm -f /etc/apt-listchanges.conf /etc/apt-listchanges.conf.old
-
-##waiting for apt 0.4## # We used to add ourselves to apt.conf; remove ourselves
-##waiting for apt 0.4## if [ -e /etc/apt/apt.conf ]; then
-##waiting for apt 0.4##         cp /etc/apt/apt.conf /etc/apt/apt.conf.old
-##waiting for apt 0.4##         (grep -v apt-listchanges /etc/apt/apt.conf.old > /etc/apt/apt.conf) || true
-##waiting for apt 0.4##         rm -f /etc/apt/apt.conf.old
-##waiting for apt 0.4##         if [ ! -s /etc/apt/apt.conf ]; then
-##waiting for apt 0.4##                 rm -f /etc/apt/apt.conf
-##waiting for apt 0.4##                 rmdir --ignore-fail-on-non-empty -p /etc/apt/
-##waiting for apt 0.4##         fi
-##waiting for apt 0.4## fi
-
 
 # dh_installdeb will replace this with shell code automatically
 # generated by other debhelper scripts.
